#!/usr/bin/env bash
#To install nginx on your web-01 server
#The Nginx should be listening on port 80
#When querying Nginx at its root / with GET request (requesting a page)
# using curl, it must return page that contains string Hello World!
apt-get update
apt-get install -y nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
service nginx restart
