#!/usr/bin/env bash
# -Displays "To infinity and beyond" indefinitely
# With  sleep 2 in between each iteration
# I am invincible!!! when receiving SIGTERM signal

while true
do 
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I am invincible!!!"' SIGTERM
done
