#!/usr/bin/env bash
# displays content of file /etc/passwd.
# Your script should only display:
#  username
#  user id
#  Home directory path for user
while read -r line; do
    echo "$line" | cut -d ':' -f 1,3,6
done</etc/passwd
