#!/usr/bin/env bash
# Write a Bash script that displays nbrs frm 1 to 20 and:
#  Displays 4 and then bad luck from China for the 4th loop iteration
#  Displays 9 and then bad luck from Japan for the 9th loop iteration
#  Displays 17 and then bad luck from Italy for the 17th loop iteration
ix=1
while [ $ix -le 20 ]
do
	echo $ix
	case $ix in
	     4) echo "bad luck from China"
	     	;;
	     9) echo "bad luck from Japan"
	        ;;
	     17) echo "bad luck from Italy"
	        ;;
        esac
	ix=$((ix+1))
done
