#!/usr/bin/env bash
# Gives info about the school file
# use if and, else (case is forbidden)
# Your script should check if the file exists and print:
  # if exists: school file exists
  # if does not exist: school file does not exist
  # If file exists, print:
  # if file is empty: school file is empty
  # if file is not empty: school file is not empty
  # if file is a regular file: school is a regular file
  # if file is not a regular file: (nothing)

if [ -e "school" ]; then
   echo "school file exists"

   if [ -s "school" ]; then
      echo "school file is not empty"
   else
      echo "school file is empty"
   fi

   if [ -f "school" ]; then
      echo "school is a regular file"
   fi
else
   echo "school file does not exist"
fi
