#!/usr/bin/env bash

# to Check if the script is run as root
if [ "$EUID" -ne 0 ]; then
    echo "Error: This script must be run as root"
    exit 1
fi

# to check if the correct number of arguments is provided
if [ "$#" -ne 1 ]; then
    echo "Usage: $0 <username>"
    exit 1
fi

# To run the whoami command under the specified user
sudo -u "$1" whoami

